# Generated by Django 5.1 on 2026-02-25 00:36

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('news_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmail_message_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('sender_name', models.CharField(max_length=255)),
                ('sender_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=500)),
                ('received_at', models.DateTimeField()),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('raw_html', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('error', 'Error')], db_index=True, default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('news_count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['status', 'received_at'], name='news_newsle_status_87dfb3_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProcessingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('started', 'Started'), ('success', 'Success'), ('error', 'Error')], max_length=20)),
                ('message', models.TextField(blank=True, default='')),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('newsletter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='news.newsletter')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('summary', models.TextField()),
                ('original_url', models.URLField(blank=True, default='', max_length=2000)),
                ('enrichment_context', models.TextField(blank=True, default='')),
                ('published_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_favorite', models.BooleanField(db_index=True, default=False)),
                ('rating', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(blank=True, null=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='articles', to='news.category')),
                ('newsletter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='news.newsletter')),
            ],
            options={
                'ordering': ['-published_at'],
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='news_articl_search__6fe81f_gin'), models.Index(fields=['is_favorite', '-published_at'], name='news_articl_is_favo_8ddc98_idx'), models.Index(fields=['rating', '-published_at'], name='news_articl_rating_bd5cbb_idx'), models.Index(fields=['is_read', '-published_at'], name='news_articl_is_read_a63e28_idx')],
            },
        ),
    ]
