# Generated by Django 5.1 on 2026-02-25 21:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0004_article_taxonomy_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsletter",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("review", "Review"),
                    ("completed", "Completed"),
                    ("error", "Error"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
    ]
