# Generated by Django 5.1 on 2026-03-03 14:25

import django.utils.timezone
from django.db import migrations, models


def seed_initial_resource(apps, _schema_editor):
    Resource = apps.get_model("news", "Resource")
    Resource.objects.get_or_create(
        resource_url=(
            "https://www.manning.com/books/build-a-reasoning-model-from-scratch?"
            "utm_source=raschka&utm_medium=affiliate&utm_campaign=book_raschka2&"
            "a_aid=raschka&a_bid=4c3c5398&chan=mm_website"
        ),
        defaults={
            "title": "Build a Reasoning Model from Scratch",
            "description": (
                "Hands-on book by Sebastian Raschka on building reasoning-capable models "
                "from first principles."
            ),
            "section": "Learning Resources",
            "category": "Books",
            "subcategory": "Reasoning Models",
            "is_featured": True,
            "is_active": True,
            "published_at": django.utils.timezone.now(),
        },
    )


def unseed_initial_resource(apps, _schema_editor):
    Resource = apps.get_model("news", "Resource")
    Resource.objects.filter(
        resource_url__startswith="https://www.manning.com/books/build-a-reasoning-model-from-scratch"
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_add_column_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, default='')),
                ('resource_url', models.URLField(max_length=2000, unique=True)),
                ('image_url', models.URLField(blank=True, default='', max_length=2000)),
                ('section', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('category', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('subcategory', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('published_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_featured', '-published_at', 'title'],
            },
        ),
        migrations.RunPython(seed_initial_resource, unseed_initial_resource),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['is_active', '-published_at'], name='news_resour_is_acti_c1ba1f_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['section', 'category', 'subcategory'], name='news_resour_section_44a043_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['is_featured', '-published_at'], name='news_resour_is_feat_f23b87_idx'),
        ),
    ]
