# Generated by Django 5.1 on 2026-03-03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0010_resource_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="preview_token",
            field=models.UUIDField(db_index=True, default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name="resource",
            name="review_comment",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="resource",
            name="review_decided_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="resource",
            name="review_notified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="resource",
            name="review_requested_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="resource",
            name="review_status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("approved", "Approved"), ("rejected", "Rejected")],
                db_index=True,
                default="approved",
                max_length=24,
            ),
        ),
        migrations.AddIndex(
            model_name="resource",
            index=models.Index(fields=["review_status", "-review_notified_at"], name="news_resour_review__c626a4_idx"),
        ),
    ]
