# Generated by Django 5.1 on 2026-03-03

from django.db import migrations, models


def backfill_source_published_at(apps, _schema_editor):
    Resource = apps.get_model("news", "Resource")
    Resource.objects.filter(source_published_at__isnull=True).update(source_published_at=models.F("published_at"))


def noop_reverse(_apps, _schema_editor):
    return None


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0011_resource_review_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="source_published_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.RunPython(backfill_source_published_at, noop_reverse),
    ]
