# Generated by Django 5.1 on 2026-03-03 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0012_resource_source_published_at"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="resource",
            new_name="news_resour_review__b07e79_idx",
            old_name="news_resour_review__c626a4_idx",
        ),
        migrations.AddField(
            model_name="resource",
            name="article_body",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="resource",
            name="summary",
            field=models.TextField(blank=True, default=""),
        ),
    ]
