# Generated by Django 5.1 on 2026-03-05 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_backfill_resource_summary_article_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('review', 'Review'), ('completed', 'Completed'), ('eliminada_pos_publicada', 'Eliminada_Pós_Publicada'), ('error', 'Error')], db_index=True, default='pending', max_length=32),
        ),
    ]
