#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
export PLUTONIA_ROOT="${PLUTONIA_ROOT:-${ROOT_DIR}}"
export PLUTONIA_DATA_DIR="${PLUTONIA_DATA_DIR:-${PLUTONIA_ROOT}/data}"
export PLUTONIA_LOG_DIR="${PLUTONIA_LOG_DIR:-${PLUTONIA_ROOT}/logs}"
export PLUTONIA_RUN_DIR="${PLUTONIA_RUN_DIR:-${PLUTONIA_ROOT}/run}"
export PLUTONIA_BACKUP_DIR="${PLUTONIA_BACKUP_DIR:-${PLUTONIA_ROOT}/backups}"
export PLUTONIA_STATIC_DIR="${PLUTONIA_STATIC_DIR:-${PLUTONIA_ROOT}/staticfiles}"
export PLUTONIA_REVIEW_DIR="${PLUTONIA_REVIEW_DIR:-${PLUTONIA_DATA_DIR}/review}"
export WATCHDOG_STATUS_FILE="${WATCHDOG_STATUS_FILE:-${PLUTONIA_REVIEW_DIR}/ops_watchdog_status.json}"

mkdir -p \
  "${PLUTONIA_DATA_DIR}" \
  "${PLUTONIA_LOG_DIR}" \
  "${PLUTONIA_RUN_DIR}" \
  "${PLUTONIA_BACKUP_DIR}" \
  "${PLUTONIA_STATIC_DIR}" \
  "${PLUTONIA_REVIEW_DIR}"
